O.a. opmerking stopzetten doorontwikkeling
VNG-Realisatie/Zaak-en-Documentservices pull request #1
Opened 2024-01-18 09:44 UTC by melsk-r

* Opmerking over het stopzetten van de doorontwikkeling toegevoegd.
* Link achter 'hier' aangepast.
* In laatste alinea voor 'Wat levert de standaard ...' werd de indruk gewekt dat deze standaard nog geadviseerd wordt. Dit is aangepast.

2024-03-06 16:01 UTC, Makkmetp commented on docs/index.md
> +dit project [hier](https://vng-realisatie.github.io/gemma-zaken/).
Volgens de digitaal toegankelijksrichtlijnen mogen verwijzigingen met het woord "hier" niet gebruikt worden.  Graag de tekst aanpassen naar "
Op de [GitHub-pagina van GEMMA-Zaken](https://vng-realisatie.github.io/gemma-zaken/) is de voortgang van het project te volgen.  
"

2024-03-06 16:02 UTC, Makkmetp requested changes
Een tekstuele wijziging vorogesteld voor in de index.md

2024-03-07 07:52 UTC, melsk-r commented on docs/index.md
> +dit project [hier](https://vng-realisatie.github.io/gemma-zaken/).
Ik heb de door jou voorgestelde zin ietwat aangepast.

2024-03-07 08:26 UTC, Makkmetp approved these changes
Ziet er goed uit. 👍🏽

2024-03-07 08:37 UTC, merged